package com.alipay.prize.model;

// Generated 2012-12-20 19:34:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.apache.struts2.json.annotations.JSON;

/**
 * Alipayer generated by hbm2java
 */
public class Alipayer implements java.io.Serializable {

	private String id;
	private String name;
	private String number;
	private String nickName;
	private String tele;
	private String flag;
	private String prizeId;
	private String desc;
	
	private Date gmtCreate;
	private Date gmtModified;

	public Alipayer() {
	}

	public Alipayer(String id, String name, String number, String nickName,
			String tele, String flag, String prizeId, String desc,
			Date gmtCreate, Date gmtModified) {
		this.id = id;
		this.name = name;
		this.number = number;
		this.nickName = nickName;
		this.tele = tele;
		this.flag = flag;
		this.prizeId = prizeId;
		this.desc = desc;
		this.gmtCreate = gmtCreate;
		this.gmtModified = gmtModified;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getTele() {
		return this.tele;
	}

	public void setTele(String tele) {
		this.tele = tele;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getPrizeId() {
		return this.prizeId;
	}

	public void setPrizeId(String prizeId) {
		this.prizeId = prizeId;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	
	public Date getGmtCreate() {
		return this.gmtCreate;
	}

	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}
	
	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

}
