package com.alipay.prize.model;

// Generated 2012-12-20 19:34:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LotteryResult generated by hbm2java
 */
public class LotteryResult implements java.io.Serializable {

	private String id;
	private String alipayerId;
	private String prizeId;
	private String alipayerName;
	private String prizeName;
	private Date gmtCreate;
	private Date gmtModified;

	public LotteryResult() {
	}

	public LotteryResult(String id, String alipayerId, String prizeId,
			String alipayerName, String prizeName, Date gmtCreate,
			Date gmtModified) {
		this.id = id;
		this.alipayerId = alipayerId;
		this.prizeId = prizeId;
		this.alipayerName = alipayerName;
		this.prizeName = prizeName;
		this.gmtCreate = gmtCreate;
		this.gmtModified = gmtModified;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAlipayerId() {
		return this.alipayerId;
	}

	public void setAlipayerId(String alipayerId) {
		this.alipayerId = alipayerId;
	}

	public String getPrizeId() {
		return this.prizeId;
	}

	public void setPrizeId(String prizeId) {
		this.prizeId = prizeId;
	}

	public String getAlipayerName() {
		return this.alipayerName;
	}

	public void setAlipayerName(String alipayerName) {
		this.alipayerName = alipayerName;
	}

	public String getPrizeName() {
		return this.prizeName;
	}

	public void setPrizeName(String prizeName) {
		this.prizeName = prizeName;
	}

	public Date getGmtCreate() {
		return this.gmtCreate;
	}

	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

}
